applications:
  blog-image-creator:
    source:
      root: "/"

    type: "nodejs:20"

    # container_profile:

    web:
      commands:
        start: "node index.js"
      upstream:
        socket_family: tcp
      locations:
        "/":
          passthru: true
          index: ['index.html']

    # workers:

    # access:

    #   env:
    #     NODE_ENV: development

    # firewall:

    build:
      flavor: none

    #   nodejs: # Specify one NPM package per line.
    #     pm2: '^4.5.0'

    hooks:
      build: |
        set -eux
        npm i
        
      deploy: |
        set -eux
        # echo 'Put your deploy command here'

      # post_deploy: |

    # crons:

    # additional_hosts:

routes:
  "https://{default}/":
    type: upstream
    upstream: "blog-image-creator:http"
  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
